# Basic dependabot.yml to update gomod

version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "development"
    directory: "/"
    schedule:
      interval: "monthly"
      # Check for npm updates at 9am UTC (5am EST)
      time: "10:00"
    reviewers:
      - "mrz1836"
    assignees:
      - "mrz1836"
    # Labels must be created first
    labels:
      - "update"
